### ISSUE TITLE
HOOBS compatibility

### ISSUE THREAD

**Issue by galzil** [homebridge/homebridge-plugin-template#11]
**Describe The Bug:**
Plugins generated from this are not working on HOOBS, 
The Error is:
`The requested platform "XXXXXX" was not registered by any plugin. Your config.json is requesting the platform`

**To Reproduce:**
Use Hoobs, install a plugin such as:
[homebridge-z2m](https://github.com/itavero/homebridge-z2m)
[homebridge-magichome-led](https://github.com/tom-23/homebridge-magichome-led)

**Expected behavior:**
plugin loads

**Logs:**

```
2.9.2020, 17:25:03 The requested platform "MagicHomeLED" was not registered by any plugin.
2.9.2020, 17:25:03 Your config.json is requesting the platform "MagicHomeLED" which has not been published by any installed plugins.
```

**Plugin Config:**

```json
{
      "platform" : "MagicHomeLED"
    }
```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: HOOBS 3.2.6
* **Node.js Version**:  v12.18.3
* **NPM Version**:  6.14.6
* **Operating System**:  Raspbian

**Comment by oznu** [comment]
HOOBS needs to update their system to support the current Homebridge API (v1.0.0). I let the people who maintain the software know what they need to do fix this about 4 months ago now.
