### ISSUE TITLE
Creating a plugin from a template

### ISSUE THREAD

**Issue by WayneKP** [homebridge/homebridge-plugin-template#12]
**Describe Your Problem:**
Hello, I am trying to create a plugin using your homebridge/homebridge-plugin-template and I am a novice but having some success but also striking some roadblocks and wanted some advice. I created a repository as per your homebridge README.md and have been working my way through your procedure, Update package.json seems OK, Update Plugin Defaults OK, Build Plugin - npm run build, I ran this in "Terminal" as I didn't know if there was some way to run in Github desktop  ?? Anyhow it created the dist and src folders etc. and when I use the "npm link" command in Terminal it creates the plugin in the Homebridge app which is I guess progress but THIS IS WHERE MY PROBLEMS BEGIN, I am assuming because I haven't Customised Plugin that Homebridge cannot communicate with my Lenovo Smart Plug to switch it on and off. I have tried tweaking the src/platform.ts, src/platformAccessory.ts and the config.scema.json files but I thinking I am screwing this up. I tried doing changes but I am getting confused because I am trying to edit on Github but that's obviously not editing my files on my computer. is it possible to create everything on Github and eventually end up with a file that I can use e.g. npm install -g homebridge-myplugin name-platform ???? I assume I will eventually be able to create and import the plugin but completing the plugin or package has got me a bit stumped at the moment if you can offer advice thanks     

Wayne

* **Plugin Version**:
* **Homebridge Version**: homebridge -1.2.3 
* **Node.js Version**: node -v12.18.4
* **NPM Version**: npm -v6.14.8 
* **Operating System**:  macOS

**Comment by donavanbecker** [comment]
@WayneKP I would recommend using visual studio code. You can run the watch script from there and watch homebridge run and this will also restart every time you save something new in the code. If you have homebridge install on your local device, this may cause issues though. You may have to uninstall that first.

**Comment by WayneKP** [comment]
Thank you for your quick response 
I have previously installed visual studio code and have been using it but more of an editor 
So if I uninstall homebridge from the local device then how can I run the watch script from there and watch homebridge run ? Which file do I run homebridge from ? Config.json ? Or do I need to run each of the .json files ?
Are there essential files that run the plugin?

Kind Regards
Wayne Pulbrook 

Mobile 0417439539
wayne_pulbrook@yahoo.com

**Comment by donavanbecker** [comment]
when you first run the watch script. it will tell you where it is trying to pull the config.json file from. Once you get the error that there isn't a config.json file at that specific location. you can add your config.json file there. 

From there it should work as expected.

**Comment by WayneKP** [comment]
Complicated but I am starting to understand more so you can close this and thanks for your help
