### ISSUE TITLE
Is there a method I can call to tell Homebridge that my device is offline / not responding?

### ISSUE THREAD

**Issue by freddieerg** [homebridge/homebridge-plugin-template#14]
Sorry, this issue should have been raised in the homebridge repo not the template.

**Describe Your Problem:**

I am creating a plugin to control a swimming pool heat pump. To do this I am using the Thermostat service. Sometimes the heat pump will disconnect from the WiFi network and when that happens I would like my plugin to be able to tell Homebridge that the accessory is offline. 

How I imagine this working is that when Homebridge or the Home app attempts to fetch new data for the accessory from the plugin, an initial condition checks the Heat Pump API to see if the device is online or offline. What I would like to know is if there is anything in the Homebridge API that I can call to report back that the device is offline? I'd preferably like to do this once for the whole accessory instead of having to implement it in every single Characteristic getter and setter. 

Sorry if this is a blindingly obvious question. I'm still trying to get comfortable with your API!

**Logs:**

```
NA
```

**Plugin Config:**

```json
{
  "pluginAlias": "NorsupHomebridgePlugin",
  "pluginType": "platform",
  "singular": true,
  "schema": {
    "type": "object",
    "properties": {
      "username": {
        "title": "Aqua Temp Username",
        "type": "string",
        "required": true,
        "default": ""
      },
      "passwordHash": {
        "title": "MD5 Hashed Password",
        "type": "string",
        "required": true,
        "default": ""
      }
    }
  }
}

```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**:  1.1.6
* **Node.js Version**:  14.7
* **NPM Version**:  6.14.7
* **Operating System**:  macOS

**Comment by oznu** [comment]
return an error in the first argument of the callback value.

eg.

https://github.com/oznu/homebridge-esp8266-garage-door/blob/master/homebridge/src/platformAccessory.ts#L86-L90

**Comment by freddieerg** [comment]
> return an error in the first argument of the callback value.
> 
> eg.
> 
> https://github.com/oznu/homebridge-esp8266-garage-door/blob/master/homebridge/src/platformAccessory.ts#L86-L90

Thanks very much for the speedy reply! This solution would definitely work but I can't help but feel without adding it to every single callback it's a little bit hacky. What would be great is if an accessory had an event for when any of the Characteristic were attempting to get or set that would cancel these attempts if the accessory was reported to be offline?

**Comment by oznu** [comment]
Not really unfortunately, you could create a wrapper function, decorator, or just a reusable function you call at the start of each get / set callback.

**Comment by freddieerg** [comment]
> Not really unfortunately, you could create a wrapper function, decorator, or just a reusable function you call at the start of each get / set callback.

Yep, sounds like a decorator might be the way to go. Thanks for your help @oznu
