### ISSUE TITLE
device/!device example is confusing

### ISSUE THREAD

**Issue by bschlenk** [homebridge/homebridge-plugin-template#17]
**Describe Your Problem:**

I'm updating an old plugin to be structured like this plugin template. The platform example has a confusing part [where device is checked](https://github.com/homebridge/homebridge-plugin-template/blob/master/src/platform.ts#L82-L100). However, the `!device` block is dead code - the device won't ever be null in this example. In what case would we want to unregister an accessory, or know that a device that used to exist no longer exists?

**Comment by oznu** [comment]
Thanks
