### ISSUE TITLE
More detail for 'First-Timers'

### ISSUE THREAD

**Issue by mitch7391** [homebridge/homebridge-plugin-template#19]
**Describe the solution you'd like:**
As someone who is trying to create their first proper plug-in and has very limited skills, I find the template README has a lot of assumed knowledge.  I was wondering if more detailed steps could be provided in more of a tutorial sort of way? In my case, I have got as far as the 'build' section but am unsure if the command to be run in the terminal is supposed to be from VS Code terminal (which fails) or if this was meant to be from somewhere else. Could more detailed steps or even a tutorial on creating a simple plug-in for first-timers be created?

**Describe alternatives you've considered:**
Not creating a plug-in, which I may be told that if I am already stuck at this stage then maybe I should not try; but I would really like to learn.

**Additional context:**
I have tried to reading over many posts and a couple 'guides' online but am not able to make the jump in how a lot of this connects.

**Comment by DylanRobinson** [comment]
I got as far as the "Customise Plugin" section before the assumed knowledge kicked in.

I expect this enhancement to be open forever so @mitch7391 if you haven't figured it out already, for the build section you need to open the node.js command prompt (or equivalent on your OS) and set the current directory to the template root, then run the command. It also assumes you have Homebridge running locally (missed in the Setup Development Environment section).

**Comment by mitch7391** [comment]
@DylanRobinson thanks for he advice and the reply; sorry for my late reply. 

I eventually gave up on this as I am focusing on using shell scripts through `homebridge-cmd4` to make do for the time being. I just do not have the spare time to work all of this out at this stage; as much as I would like to. I guess what I am hoping for (and what I have done on my repos) is what we call a Single Point Lesson (SPL) in my line of work. This is literally a dummies step by step guide of what to do so that a first-timer can complete the task without fail (and hopefully learn from there how to do it again or do more in future).

**Comment by mitch7391** [comment]
Thought I would add some more details here after coming back to this two years later and applying some skills I have learned along the way from a 'sudo plug-in' that I maintain that has a Homebridge verified UI. I currently am trying to make a stand-alone plug-in using this template and have Homebridge side of things working with GitHub.

Personally I do not bother with VS Code and this was what I could not get to work years ago, but looking back I am sure the principles are the same, just a different dev environment. I use my Raspberry Pi as my dev environment as that is where my Homebridge instance lives and the following steps assume you do too and have a working RPi Homebridge setup already.

1. Clone the template using the link provided on the template `README`.
2. Towards the top of your new GitHub page, you will find a green `<> Code` button; click this and then click 'copy to clipboard' button to the right of your url.

![image](https://user-images.githubusercontent.com/40288237/221403960-0cc0c325-257a-4ddb-ae13-d06a794a0f96.png)

3. Use the terminal of your RPi through whatever method you normally use and navigate to /tmp:

```shell
cd /tmp
```
4. You can follow up with a `ls -al` to see what is in the directory.
5. Type the following with your copied url (without the <>) to clone your new repo to you RPi:

```shell
git clone <url>
```
6. Once this is done, navigate into the directory (replace `homebridge-repo-name` with the name of your plug-in):
```shell
cd homebridge-repo-name
```
7. Now install the development dependencies as per the template README:
```shell
npm install
```
8. Follow the rest of the instructions as per the template README for customising your plug-in.

I do all of my dev work directly via the terminal, but you can use VNC or anything else to create a remote desktop session to use other editors. Once I have made my changes, from the terminal I will use the following commands:

1. Check what files I have changed: `git status`.
2. Accept my changes and add the changed files to the commit: `git add <file1> <file2> <file3>`.
3. Run `eslint` checks (if you have any warnings, GitHub workflow will reject the push): `npm run lint`.
4. To fix any `eslint` errors and warnings: `npm run lint --fix`.
5. Next it is worth making sure it builds and can convert from TypeScript to JavaScript: `npm run build`.
6. If steps 3-5 worked and are now happy, GitHub workflow should not reject your changes when pushed.
7. To make my commit and add commit notes: `git commit`.
8. Push the changes back to GitHub: `git push`.
9. It will then ask for your login details to verify you are you.
10. At any time, use `npm link` to link your plug-in to your local Homebridge and see how it goes.

Another handy use is if you have created a beta branch in GitHub. Use `git switch beta` or `git switch master` to switch between your branches while in `/tmp/homebridge-repo-name`. If committing and then pushing to your beta branch in GitHub, you may need to use `git push origin beta` for step 8.

Really hopes this helps someone else, as I am now finally getting somewhere and building the actual logic to my plug-in and learning TypeSript/JavaScript as I go.
