### ISSUE TITLE
The README section "Update package.json" should note the "name" should not be mixed case.

### ISSUE THREAD

**Issue by oogje** [homebridge/homebridge-plugin-template#21]
**Is your feature request related to a problem? Please describe:**
When I tried to "npm unpublish homebridge-bigAssFans-i6 --force" it failed silently.   I contacted support  the following day because the package was not unpublished.  Per npm@githubsupport.com: "Please keep in mind that package names are case sensitive and mixed case names are not supported. That might be why your attempt to unpublish homebridge-bigAssFans-i6 failed."

**Describe the solution you'd like:**
In the README where it says the name should "contain no spaces or special characters apart from a dashes" perhaps it should say "contain no spaces or special characters apart from dashes, nor be mixed case" or some such.  By the way "a dashes" looks like a typo.

**Describe alternatives you've considered:**
none

**Additional context:**
thank you

**Comment by bwp91** [comment]
Hi @oogje thanks for this comment. I have updated README:
https://github.com/homebridge/homebridge-plugin-template/blob/main/README.md#update-packagejson
So will close this, please feel free to reopen if needed!
