### ISSUE TITLE
Possible to controle already existing device ? 

### ISSUE THREAD

**Issue by noenic** [homebridge/homebridge-plugin-template#24]
Hi , Hum... I don't know anything actually about making HB plugins,
But i have Camera that i added to Homekit with the RTSP plugin and with it got a dummy motion sensor.
Since i can use ONVIF request to get real values from the camera's motion sensor.
I got it to work on python with pyhomebridge but it was not a very good idea since it use HTTP request to trigger the switch (making a request on the same computer is not the best idea) and it use python what is not the final goal..
Is there a way to get access to switches and other devices from homebridge and controlling them.

thanks

**Comment by bwp91** [comment]
Closing as over 2 years old. Please feel free to reopen if needed!
