### ISSUE TITLE
.npmignore should not exclude dist

### ISSUE THREAD

**Issue by Kubiac** [homebridge/homebridge-plugin-template#27]
**Describe The Bug:**
When you want to publish your plugin (npm publish) it cannot be installed by other npm users because the dist-directory is excluded from the tar-ball.

**To Reproduce:**
npm publish on dev machine
npm install on user machine

**Expected behavior:**
plugin is correctly installed and can be loaded by homebridge

**Logs:**

```
[11/14/2021, 11:58:39 PM] ERROR LOADING PLUGIN homebridge-xxx:
[11/14/2021, 11:58:39 PM] Error: Cannot find module '/usr/lib/node_modules/homebridge-xxx/dist/index.js'
Require stack:
- /usr/lib/node_modules/homebridge/lib/plugin.js
- /usr/lib/node_modules/homebridge/lib/pluginManager.js
- /usr/lib/node_modules/homebridge/lib/server.js
- /usr/lib/node_modules/homebridge/lib/cli.js
- /usr/lib/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Plugin.load (/usr/lib/node_modules/homebridge/src/plugin.ts:192:73)
    at PluginManager.initializeInstalledPlugins (/usr/lib/node_modules/homebridge/src/pluginManager.ts:131:22)
    at Server.start (/usr/lib/node_modules/homebridge/src/server.ts:156:5)
```

**Plugin Config:**
na

**Screenshots:**
na

**Environment:**

* **Plugin Version**: na
* **Homebridge Version**: na
* **Node.js Version**: v17.0.1
* **NPM Version**: 8.1.0
* **Operating System**: macOS

**Comment by bimusiek** [comment]
+1 This is a bump in the road for new homebridge plugin developer. I was publishing my first ever package and did not have a clue that `dist` could be ignored when publishing to npm.

**Comment by NorthernMan54** [comment]
@bimusiek I was looking into this as I had never ran into this with my plugins, and found an unexpected behaviour from npm and a package.json setting.

In my package.json, I had main including the dist directory

https://github.com/NorthernMan54/homebridge-tasmota/blob/master/package.json#L18

And this triggered the npm packager to include the dist directory.  When I removed dist from main, the dist directory was not longer included within the npm package.

So this explains why such a simple issue passed testing.

But with that said, I will submit a pull request to remove dist from .npmignore to reduce the risk of someone else getting tripped up by this.

**Comment by bimusiek** [comment]
@NorthernMan54 Hey, so in my case the dist/index.js was indeed uploaded to npm. However, no other files from dist were. So when index.js was including settings.js I was getting errors on homebridge that the dist/settings.js does not exist. 

Thanks for fixing the issue :) And cudos on creating great template, super easy to start development on homebridge plugins!

**Comment by NorthernMan54** [comment]
@bimusiek please send all the kudos to @oznu, this is his inspiration.
