### ISSUE TITLE
Disable current plugin?

### ISSUE THREAD

**Issue by chriscn** [homebridge/homebridge-plugin-template#3]
1) Is there any documentation available for homebridge?
2) How could I disable the current plugin, for instance if the login function failed?

Thanks <3

**Comment by oznu** [comment]
The easist way to do this would be to not create the accessory handler instance if the login failed.

Assuming you login in `platform.ts`, you can move around the logic to create the handler for restored cached accessories at a later time.

https://github.com/homebridge/homebridge-plugin-template/blob/master/src/platform.ts#L44-L46

Un-initialised restored accessories won't be able to do anything in the Home app, but they won't break the anything in this state either.

**Comment by oznu** [comment]
Template adjusted not to "init" accessories until they have been "discovered"
