### ISSUE TITLE
Debug logs is not shown without adding plugin to homebridge configuration

### ISSUE THREAD

**Issue by hugolundin** [homebridge/homebridge-plugin-template#33]
**Describe The Bug:**

I followed the instructions in the README, but when running (with `npm run watch`) no logs from my plugin were printed to stdout. 

**Expected behavior:**

The plugin should load and logs should be shown. I expect the instructions for this to happen (change the config) to be in the README. 

**Plugin Config:**

The problem was solved by adding a platform in my config. This was **not mentioned anywhere in the README**. 

```json

{
    "bridge": {
        "name": "******",
        "username": "*******",
        "port": *****,
        "pin": "*****"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "name": "Platform name",
            "platform": "<plugin platform name>"
        }
    ]
}


```

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 1.4.0
* **Node.js Version**: v17.8.0
* **NPM Version**: 8.5.5
* **Operating System**: macOS

It would be helpful for beginners to provide instructions about this. I found the solution by accident on the homebridge Discord but it could be a blocker for people when starting out :)

**Comment by SuperJoran** [comment]
Thank you, this helped me.

To add to this, <plugin platform name> should of course be replaced by the PLATFORM_NAME you defined in the settings.ts file.

You might not even have a config.js file like me. If you follow the complete instruction for your platform (https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-macOS) this file will be created.

**Comment by bwp91** [comment]
Closing. I haven't personally made any changes to the README with regards to this issue, but I can see in the README now that a `platform` property exists in the example config:
https://github.com/homebridge/homebridge-plugin-template#watch-for-changes-and-build-automatically

If I haven't quite understood what you are saying here or need to reopen this issue, please feel free to do so!
Thanks
