### ISSUE TITLE
What is that ?

### ISSUE THREAD

**Issue by TapsHTS** [homebridge/homebridge-plugin-template#34]
**Describe Your Problem:**
I want to add this, can you tell me the name or give me the doc page about this: (screenshot)

PS: If you can show me the code ❤

**Logs:**

❌

**Plugin Config:**

❌

**Screenshots:**
![image](https://user-images.githubusercontent.com/61658427/174493401-8270f747-5916-4657-8312-fd7f8d0c418d.png)

**Environment:**

* **Plugin Version**:  ❌
* **Homebridge Version**: 1.4.1
* **Node.js Version**:  v16
* **NPM Version**:  v6 
* **Operating System**: Raspbian

**Comment by oznu** [comment]
https://developers.homebridge.io/#/service/Television
