### ISSUE TITLE
Good Examples of Multi Accessory Platform Plugins To Follow

### ISSUE THREAD

**Issue by mitch7391** [homebridge/homebridge-plugin-template#51]
**Describe Your Problem:**

I am starting to work on my very first plug-in off this template and have the template all up and running; first with the dummy accessories and now have started testing the waters of changing those accessories to type Switch with a Temperature Sensor service added that is actually reading from my device.

Eventually I will need to create a Thermostat accessory, a Fan accessory and many more. I know that it is said that we are to create a separate `platformAccessory.ts` for each accessory but am not finding good examples of plug-ins that do multiple accessories in this manner. The Homebridge example plug-ins do not follow the method of this plug-in template and a lot of older plug-ins put all logic in one `index.js` file. 

What I am after is an example of a plug-in that uses `platform.ts` for device setup and discovery and has multiple versions of the `platformAccessory.ts` file for accessory logic; preferably an example that Homebridge would endorse and like new devs to follow.

**Logs:**

```
N/A
```

**Plugin Config:**

```json
N/A
```

**Screenshots:**

**Environment:**

* **Plugin Version**: N/A
* **Homebridge Version**:  N/A
* **Node.js Version**:  N/A
* **NPM Version**:  N/A
* **Operating System**:  N/A

**Comment by mitch7391** [comment]
@donavanbecker sorry to tag you directly, but you were one of the most recently active devs on here that I have seen.

**Comment by NorthernMan54** [comment]
@mitch7391 for an example, take a look at my homebridge-tasmota plugin, it creates various device types based on the tasmota device discovered.

**Comment by mitch7391** [comment]
@NorthernMan54 thank you so much for pointing me towards your work, I have just had a quick skim over it and looks to be exactly the example I was after :) I will take some time to go over it properly soon!

**Comment by bwp91** [comment]
Closing this now, please feel free to re-open if needed!
