### ISSUE TITLE
EACCES: permission denied

### ISSUE THREAD

**Issue by peterrakolcza** [homebridge/homebridge-plugin-template#60]
**Describe Your Problem:**
I have installed homebridge from the package manager (latest Ubuntu), however when I try to link the template plugin I get permission denied. I used `sudo hb-service link` command.

**Logs:**

![image](https://github.com/homebridge/homebridge-plugin-template/assets/6462276/6b82c907-dde3-424f-bdd9-71354d536f9b)

**Plugin Config:**

There are no plugins installed, I am trying to develop my first plugin using the default template.

**Environment:**

* **Plugin Version**: Default templage
* **Homebridge Version**: 1.6.1
* **Node.js Version**: v21
* **NPM Version**: 10.2
* **Operating System**: Ubuntu

**Comment by peterrakolcza** [comment]
Running as root solved my issue, however this is a temporary fix I think...
[Running as root](https://www.reddit.com/r/homebridge/comments/urxivs/running_homebridge_as_root_after_may_2022_update/)

**Comment by chasenicholl** [comment]
Thanks for the feedback, if running as root fixed your problem this has to do with your installation of Homebridge. Thanks again!
