### ISSUE TITLE
Warning to log if nodes upgraded to version 20...

### ISSUE THREAD

**Issue by dkerr64** [homebridge/homebridge-plugin-template#62]
Plugins built from this template generate a warning error in Homebridge log after nodejs is upgraded to version 20, which is now the default...

`The plugin "<name-your-pligin>" requires Node.js version of ^18.17.0 which does not satisfy the current Node.js version of v20.9.0. You may need to upgrade your installation of Node.js - see https://homebridge.io/w/JTKEF`

The `package.json` file in this template should be updated to permit higher nodejs versions by default.

**Comment by donavanbecker** [comment]
Please open a PR.

**Comment by dkerr64** [comment]
What is your preferred solution?
`"node": ">=18.17.0"`
or 
`"node": "^18.17.0 || ^20.9.0"`

**Comment by donavanbecker** [comment]
2nd

**Comment by NorthernMan54** [comment]
Minimums are 18.15, 20 and 21

18.15 is for Synology DSM

**Comment by dkerr64** [comment]
> Minimums are 18.15, 20 and 21
> 
> 18.15 is for Synology DSM

This is just a _template_, plugins can adjust as necessary.  Homebridge currently recommends minimum of 18.17 and that is what this template had, so I wasn't going to change it to an earlier version.  Similarly, Homebridge only officially supports even-numbered versions of Node so adding 21.x.x to the template would be inappropriate.

My objective was simply to ask the maintainer to update the template so that new plugins built from it would not immediately issue a warning message when Node 20 is used (as is now the default I think).  He turned around and asked that I open a PR, which I have done (PR #63).  But it is not for me to determine what the actual version numbers in the template should be, that is for the maintainer.
